name: golang bindings ci

on:
  push:
    branches: [main]
  pull_request: {}
  merge_group: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  branch_name: ${{ github.head_ref || github.ref_name }} # https://stackoverflow.com/a/71158878
  bucket_name: "main"

jobs:
  go-test:
    runs-on: depot-ubuntu-24.04-16
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 2

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
      - name: Cache cargo index
        uses: actions/cache@v4
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-git-${{ hashFiles('**/Cargo.lock') }}
      - name: Cache cargo build
        uses: actions/cache@v4
        with:
          path: rust/target
          key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}
      - name: Build
        working-directory: ./
        run: cargo build --release --verbose
      - name: List current directory contents
        run: ls -la
      - name: List current target contents
        run: ls -la target
      - name: List current release contents
        run: ls -la target/release

      - name: Set up Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          cache: false
          go-version-file: go-bindings/go.mod

      - name: Get Go environment
        id: go-env
        working-directory: go-bindings/
        run: |
          GOCACHE="$(go env GOCACHE)"
          GOMODCACHE="$(go env GOMODCACHE)"
          GOVERSION="$(go env GOVERSION)"
          echo "GOCACHE=${GOCACHE}" >>"${GITHUB_OUTPUT}"
          echo "GOMODCACHE=${GOMODCACHE}" >>"${GITHUB_OUTPUT}"
          echo "GOVERSION=${GOVERSION}" >>"${GITHUB_OUTPUT}"

      # https://github.com/actions/setup-go/issues/358
      # https://github.com/actions/setup-go/issues/478
      - name: Set up Go cache
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: |
            ${{ steps.go-env.outputs.GOCACHE }}
            ${{ steps.go-env.outputs.GOMODCACHE }}
          key: ${{ github.workflow }}-${{ github.job }}-${{ runner.os }}-${{ runner.arch }}-${{ steps.go-env.outputs.GOVERSION }}-${{ hashFiles('go.mod') }}

      - name: Install tokenizers
        run: make install-tokenizers

      - name: Run Go tests
        working-directory: go-bindings
        run: |
          go env -w GOPRIVATE=github.com/cohere-ai
          go test ./...
